ARG KERNEL_VERSION="5.10"
ARG KERNEL_REVISION="104"

FROM --platform=linux/amd64 ubuntu:20.04 AS build
ARG KERNEL_VERSION
ARG KERNEL_REVISION
ARG PUBLIC_SOURCES
WORKDIR /sdk
RUN apt-get update -qq
RUN apt-get install -yqq wget build-essential flex bison libssl-dev bc xxd
RUN wget -q https://developer.download.nvidia.com/embedded/L4T/bootlin/aarch64--glibc--stable-final.tar.gz
RUN tar xf aarch64--glibc--stable-final.tar.gz
WORKDIR /src

RUN wget -q https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/sources/public_sources.tbz2
RUN tar xf public_sources.tbz2
WORKDIR /src/Linux_for_Tegra/source/public
RUN tar xf kernel_src.tbz2
ENV CROSS_COMPILE_AARCH64_PATH=/sdk/aarch64-buildroot-linux-gnu
ENV CROSS_COMPILE_AARCH64=/sdk/bin/aarch64-buildroot-linux-gnu-
COPY tegra_defconfig_extra ./
RUN cat tegra_defconfig_extra >> ./kernel/kernel-${KERNEL_VERSION}/arch/arm64/configs/tegra_defconfig
RUN ./nvbuild.sh

FROM scratch AS final
ARG KERNEL_VERSION
ARG KERNEL_REVISION
COPY --from=build /src/Linux_for_Tegra/source/public/kernel/kernel-${KERNEL_VERSION}/net/netfilter/ipset/*.ko /lib/modules/${KERNEL_VERSION}.${KERNEL_REVISION}-tegra/kernel/net/netfilter/ipset/
COPY --from=build /src/Linux_for_Tegra/source/public/kernel/kernel-${KERNEL_VERSION}/net/netfilter/xt_nfacct.ko /lib/modules/${KERNEL_VERSION}.${KERNEL_REVISION}-tegra/kernel/net/netfilter/
COPY --from=build /src/Linux_for_Tegra/source/public/kernel/kernel-${KERNEL_VERSION}/net/sched/em_ipset.ko /lib/modules/${KERNEL_VERSION}.${KERNEL_REVISION}-tegra/kernel/net/sched/
COPY --from=build /src/Linux_for_Tegra/source/public/kernel/kernel-${KERNEL_VERSION}/fs/xfs/xfs.ko /lib/modules/${KERNEL_VERSION}.${KERNEL_REVISION}-tegra/kernel/fs/xfs/
