FROM --platform=linux/amd64 ubuntu:22.04 AS build
WORKDIR /sdk
RUN apt-get update -qq
RUN apt-get install -yqq wget build-essential flex bison libssl-dev bc xxd rsync sudo
RUN wget -q https://developer.download.nvidia.com/embedded/L4T/bootlin/aarch64--glibc--stable-final.tar.gz
RUN tar xf aarch64--glibc--stable-final.tar.gz
WORKDIR /src

RUN wget -q https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/sources/public_sources.tbz2
RUN tar xf public_sources.tbz2
WORKDIR /src/Linux_for_Tegra/source
RUN tar xf kernel_src.tbz2
RUN tar xf kernel_oot_modules_src.tbz2
RUN tar xf nvidia_kernel_display_driver_source.tbz2
ENV CROSS_COMPILE_PATH=/sdk/aarch64-buildroot-linux-gnu
ENV CROSS_COMPILE=/sdk/bin/aarch64-buildroot-linux-gnu-
COPY tegra_defconfig_extra ./
RUN cat tegra_defconfig_extra >> ./kernel/kernel-jammy-src/arch/arm64/configs/defconfig
RUN ./nvbuild.sh
ENV INSTALL_MOD_PATH=/target
RUN mkdir -p /target/boot
RUN ./nvbuild.sh -i
RUN find /target

FROM scratch AS final
COPY --from=build /target/ /
